name: Lint packages

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies and build # build is a postinstall script
        run: yarn --immutable
      - name: Lint packages
        run: yarn lint
