name: Lint packages

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
      - name: Install dependencies and build # build is a postinstall script
        run: pnpm install --frozen-lockfile
      - name: Lint packages
        run: pnpm lint
