name: Test packages

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies and build # build is a postinstall script
        run: yarn --immutable
      - name: Test packages
        run: |
          yarn workspaces foreach -v --exclude root --exclude @fig/publish-spec-to-team run test
          yarn workspace @fig/publish-spec-to-team run test # TODO(fedeci): investigate why this works when run separated
