name: 'Update @withfig/autocomplete-tools spec'
on:
  push:
    tags:        
      - '@withfig/autocomplete-tools@*'
  workflow_dispatch:

jobs:
  push-to-fig-autocomplete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: |
          yarn
          yarn workspace @withfig/autocomplete-tools generate-spec > generated.ts
      - name: 'Create Autocomplete PR'
        uses: withfig/push-to-fig-autocomplete-action@v1
        with:
          token: ${{ secrets.FIG_BOT_TOKEN }}
          autocomplete-spec-name: '@withfig/autocomplete-tools'
          spec-path: generated.ts
          integration: commander
