name: Update Docs & Website

on:
  workflow_dispatch:
  push:
    paths:
      - "types/index.d.ts"

jobs:
  update-docs:
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.FIG_BOT_TOKEN }}
        repository: withfig/public-site-nextjs
        event-type: autocomplete-docs
