name: 'Update create-completion-spec spec'
on:
  push:
    tags:        
      - 'create-completion-spec@*'
  workflow_dispatch:

jobs:
  push-to-fig-autocomplete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
      - run: |
          pnpm install
          pnpm run --filter ./cli/create-completion-spec generate-spec > generated.ts
      - name: 'Create Autocomplete PR'
        uses: withfig/push-to-fig-autocomplete-action@v1
        with:
          token: ${{ secrets.FIG_BOT_TOKEN }}
          autocomplete-spec-name: 'create-completion-spec'
          spec-path: generated.ts
          integration: commander
